.travis.yml
OptimizelySDK/OptimizelyTests/OptimizelyTests-Common/DatafileHandlerTests.swift

use iOS 12.1, 11.4 and 9.1.  Also use tvoOS 12.1.  This targets the OSs with the most market share.

(chore): Udate travis os builds

---

CHANGELOG.md
OptimizelySDK/Customization/DefaultEventDispatcher.swift

made the event handler run every minute.

(chore): Tighten down event dispatch interval

---

Sources/Utils/AtomicProperty.swift

changed the dispatch queue to use concurrent queue for reads and async with barrier for writes.

(fix) : update atomic property to use read write locks

---

OptimizelySwiftSDK.xcodeproj/project.pbxproj
Sources/Customization/DefaultEventDispatcher.swift
Sources/Data Model/ProjectConfig.swift
Sources/Extensions/ArrayEventForDispatch+Extension.swift
Sources/Implementation/Datastore/DataStoreQueueStackImpl.swift
Sources/Optimizely/OptimizelyError.swift
Sources/Utils/Notifications.swift
Tests/OptimizelyTests-Common/EventDispatcherTests.swift
Tests/OptimizelyTests-Common/EventDispatcherTests_Batch.swift
Tests/TestData/empty_datafile_new_account_id.json
Tests/TestData/empty_datafile_new_project_id.json
Tests/TestData/empty_datafile_new_revision.json

* Add flush on {batchSize hit, revision change, project id change}
* Clean up batch (batch as much as possible instead of falling back to a single event mode when batch failure detected in an event group)
* Support maxQueueSize (configurable)
* Add many more unit tests to increase coverage
* Event notification is not included in this PR. It'll be prepared in a separate PR.

feat(event processor): change batching to be compliant with Event Processor

---

.travis.yml
Sources/Customization/DefaultEventDispatcher.swift
Sources/Data Model/ProjectConfig.swift
Tests/OptimizelyTests-Common/EventDispatcherTests.swift
Tests/OptimizelyTests-Common/EventDispatcherTests_Batch.swift

* when timerInterval is negative, spec defines to use default interval value (instead of disabling batch).

fix(event processor): change ep behavior when timerInterval is negative value

---

DemoSwiftApp/AppDelegate.swift
OptimizelySwiftSDK.xcodeproj/project.pbxproj
Podfile.lock
Sources/Customization/DefaultEventDispatcher.swift
Sources/Customization/Protocols/OPTEventDispatcher.swift
Sources/Optimizely/OptimizelyClient.swift
Sources/Utils/Constants.swift
Tests/OptimizelyTests-Common/EventDispatcherTests_Batch.swift

- async event dispatch and notification makes testing complicated (timing control)
- add an extra API call: close() for testing support only
- it stops datafile polling and flush all events synchronously

fix: add close() API to OptimizelyClient and EventDispatcher for test support

---

.travis.yml

Upgrade travis xcode to 11.3 to include iOS13 devices in testing
- With this upgrade, travis drops iOS9 and 10. Upgrade them to iOS11+

chore: upgrade travis xcode to 11.3 and simulators to OS13

---

OptimizelySwiftSDK.xcworkspace/xcshareddata/IDETemplateMacros.plist
Scripts/change_header/header.template

Update copyright year to 2020 in license templates for new files.

chore: update license header template to 2020

---

OptimizelySwiftSDK.xcodeproj/project.pbxproj
Sources/Implementation/DefaultDatafileHandler.swift
Sources/Optimizely/OptimizelyClient+ObjC.swift
Sources/Optimizely/OptimizelyClient.swift
Sources/Protocols/OPTDatafileHandler.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_DatafileHandler.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_Init_Async.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_Init_Sync.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_ObjcAPIs.m
Tests/OptimizelyTests-APIs/OptimizelyClientTests_OptimizelyConfig.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_Others.swift
Tests/OptimizelyTests-Common/DatafileHandlerTests.swift
Tests/OptimizelyTests-Common/EventDispatcherTests_Batch.swift

* Add an option to dynamically update ProjectConfig on datafile cache update for sync init flow (this feature is disabled by default to be compatible with the old versions).
* When periodic polling is enabled, the sync cache change always update ProjectConfig dynamically regardless of the setting above.

fix: sync init flow changed to support dynamic update

---

DemoObjCApp/AppDelegate.m
DemoObjCApp/DemoObjcApp.xcodeproj/xcshareddata/xcschemes/DemoObjciOS.xcscheme
DemoObjCApp/DemoObjcApp.xcodeproj/xcshareddata/xcschemes/DemoObjctvOS.xcscheme
DemoSwiftApp/AppDelegate.swift
DemoSwiftApp/DemoSwiftApp.xcodeproj/project.pbxproj
DemoSwiftApp/DemoSwiftApp.xcodeproj/xcshareddata/xcschemes/DemoSwiftiOS.xcscheme
DemoSwiftApp/DemoSwiftApp.xcodeproj/xcshareddata/xcschemes/DemoSwifttvOS.xcscheme
DemoSwiftApp/Samples/SamplesForAPI.swift
OptimizelySwiftSDK.xcodeproj/xcshareddata/xcschemes/OptimizelySwiftSDK-Commons.xcscheme
OptimizelySwiftSDK.xcodeproj/xcshareddata/xcschemes/OptimizelySwiftSDK-DataModels.xcscheme
OptimizelySwiftSDK.xcodeproj/xcshareddata/xcschemes/OptimizelySwiftSDK-iOS.xcscheme
OptimizelySwiftSDK.xcodeproj/xcshareddata/xcschemes/OptimizelySwiftSDK-tvOS.xcscheme
OptimizelySwiftSDK.xcodeproj/xcshareddata/xcschemes/OptimizelySwiftSDKTests-Common-tvOS.xcscheme
OptimizelySwiftSDK.xcodeproj/xcshareddata/xcschemes/OptimizelyTests-Commons-iOS.xcscheme
OptimizelySwiftSDK.xcodeproj/xcshareddata/xcschemes/OptimizelyTests-DataModel-tvOS.xcscheme
OptimizelySwiftSDK.xcodeproj/xcshareddata/xcschemes/OptimizelyTests-DataModels-iOS.xcscheme
OptimizelySwiftSDK.xcodeproj/xcshareddata/xcschemes/OptimizelyTests-Others-iOS.xcscheme
OptimizelySwiftSDK.xcodeproj/xcshareddata/xcschemes/OptimizelyTests-Others-tvOS.xcscheme
Sources/Extensions/OptimizelyClient+Extension.swift
Sources/Optimizely/OptimizelyClient+ObjC.swift
Sources/Optimizely/OptimizelyClient.swift
Sources/Optimizely/OptimizelyConfig+ObjC.swift
Sources/Optimizely/OptimizelyConfig.swift
Tests/OptimizelyTests-Common/DecisionListenerTests.swift

* SDK init with and without polling are controlled with separate init methods, which conflict with each other. Cleaned up.
* Improved SDK initialization samples

refact: clean up SDK init methods with polling control

---

Sources/Data Model/FeatureVariable.swift
Sources/Optimizely/OptimizelyClient+ObjC.swift
Sources/Optimizely/OptimizelyClient.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_Invalid.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_ObjcAPIs.m
Tests/OptimizelyTests-APIs/OptimizelyClientTests_Others.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_Valid.swift
Tests/OptimizelyTests-Common/DecisionListenerTests.swift
Tests/OptimizelyTests-DataModel/FeatureVariableTests.swift
Tests/TestData/api_datafile.json

- added GetFeatureVariableJSON API.
- FSC should pass.
- Added Unit tests.

feat: added GetFeatureVariableJSON.

---

Sources/Optimizely/OptimizelyClient.swift

During evaluations of which `start` method we should use in our project, we discovered that in the async initialization, the `resourceTimeout` is not forwarded to the `datafileHandler`. This will be fixed with this PR.

Forward resourceTimeout to datafileHandler

---

Sources/Optimizely/OptimizelyClient.swift
Tests/OptimizelyTests-Common/DecisionListenerTests.swift

- Fixed an issue with decision notification where `OptimizelyJSON` object was being sent as variable value instead of a map.
- FSC should pass with FEATURE_JSON tag.
- Updated unit tests accordingly.
https://optimizely.atlassian.net/browse/OASIS-6427

fix(OptimizelyJSON): Send map instead of OptimizelyJSON object in decision notification.

---

Sources/Implementation/DefaultDecisionService.swift
Tests/OptimizelyTests-Common/DecisionServiceTests_Features.swift

- fixes target-rollout error continuing other rules when a rule hits but bucketing fails.
- FSC should pass.
- Updated unit tests accordingly.
- https://optimizely.atlassian.net/browse/OASIS-6334

fix: Targeting rollout should move to fallback rule when bucketing fails.

---

OptimizelySwiftSDK.podspec
OptimizelySwiftSDK.xcodeproj/project.pbxproj
OptimizelySwiftSDK.xcodeproj/xcshareddata/xcschemes/OptimizelySwiftSDK-macOS.xcscheme
OptimizelySwiftSDK.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
Package.swift
Sources/Protocols/BackgroundingCallbacks.swift
Sources/Supporting Files/Optimizely.h

I noticed that the changes required to get this working on macOS were minimal. As I'd like to use this SDK on a macOS client I'm working on, I went ahead and made those changes. Let me know if there's anything you'd like me to add/fix/change; happy to do the work.
- I tested this on both carthage and SPM. I did not test it on cocoapods, however I made modifications to the podspec based solely on documentation. Would love feedback here if there's anything else I need to do to get cocoapods support.
- I did some minimal real world testing on macOS (fetching feature booleans/variables), but not much aside from that. If there's anything you'd like me to test more, please let me know.
Since compatibility changes here are minimal, the macOS version of the framework is essentially identical to …

Add macOS Compatibility

---

Sources/Optimizely/OptimizelyJSON.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_OptimizelyJSON.swift

- `jsonPath` parameter for `getValue` method changed to non-null as default.
https://optimizely.atlassian.net/browse/OASIS-6753

refact(getValue): Simplifying getValue by default nil value for jsonPath.

---

Sources/Data Model/Audience/SemanticVersion.swift
Tests/OptimizelyTests-DataModel/SemanticVersionTests.swift

add unit tests and fail invalid versions and prerelease is always less than release.

fix: fix tests that failed on FSC

---

Sources/Data Model/Audience/SemanticVersion.swift
Tests/OptimizelyTests-DataModel/SemanticVersionTests.swift

- Add a check to make sure that the dot notated prefix is a number.

fix: add check to see that all dot notated areas are numbers.

---

.travis.yml
Scripts/start_simulator.sh

- Fix an error in travis.yml (unit test simulator is not synced with its name)
- Add a command for dump available simulators when failed to launch the simulator

chore: fix a simulator name error

---

Sources/Data Model/DispatchEvents/BatchEvent.swift
Sources/Implementation/Events/BatchEventBuilder.swift
Sources/Optimizely/OptimizelyClient.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_Others.swift
Tests/OptimizelyTests-Common/BatchEventBuilderTests_Events.swift

- added "enabled" field to decision metadata structure
- setting "enabled" to true for activate() since we check for non nil variation.

feat: added "enabled" field to decision metadata structure.

---

Sources/Optimizely+Decide/OptimizelyDecision.swift
Sources/Optimizely+Decide/OptimizelyUserContext.swift

Clone the current user-context and pass it to optimizely.decide()
- user context can be changed while processing the decide request.
- with this fix, decide can return the copy of the original user-context as a part of the decision

feat(decide): clone user-context before calling optimizely decide

---

DemoSwiftApp/AppDelegate.swift
Sources/Implementation/DecisionInfo.swift
Sources/Implementation/Events/BatchEventBuilder.swift
Sources/Optimizely+Decide/OptimizelyClient+Decide.swift
Sources/Optimizely+Decide/OptimizelyDecision.swift
Sources/Optimizely+Decide/OptimizelyUserContext.swift
Sources/Optimizely/OptimizelyClient.swift
Sources/Optimizely/OptimizelyError.swift
Sources/Optimizely/OptimizelyJSON.swift
Tests/OptimizelyTests-Common/BatchEventBuilderTests_Events.swift
Tests/OptimizelyTests-Common/DecisionListenerTests.swift
Tests/OptimizelyTests-Common/OptimizelyUserContextTests_Decide.swift

RuleKey or VariationKey can be nil in decision flag notification.
To avoid they are removed from decisionInfo map, change them to NSNull (consistent with other decision notifications).

fix(decide): change nil to NSNull for decision flag notification

---

.travis.yml
OptimizelySwiftSDK.xcodeproj/project.pbxproj
Sources/Customization/DefaultDatafileHandler.swift
Sources/Customization/Protocols/OPTDatafileHandler.swift
Sources/Extensions/OptimizelyClient+Extension.swift
Sources/Implementation/Datastore/DataStoreFile.swift
Sources/Implementation/DefaultDatafileHandler.swift
Sources/Optimizely/OptimizelyClient.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_Init_Async.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_Init_Sync.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_OptimizelyConfig.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_Others.swift
Tests/OptimizelyTests-Common/DatafileHandlerTests.swift
Tests/OptimizelyTests-Common/DecisionListenerTests.swift

As consumers of the SDK we have a need to support custom reading and writing of the data files within Optimizely. This PR makes changes to allow for this customization by supporting the injection of an `OPTDatafileHandler` that can implement these custom behaviors.
There are three main areas of this PR:
* Allow for injecting a `OPTDatafileHandler` during the construction of the `OptimizelyClient`. If not supplied then the standard `DefaultDatafileHandler` is utilized. 
* Open the existing implementation of `DefaultDatafileHandler` so that it can be extended by consumers of the SDK and injected via `OptimizelyClient` construction.
* Open the existing implementation of `DataStoreFile` so that it can be easily extended to support custom reading and writing of `Data`, and utilized in extended …

Allow supplying data file handler.

---

DemoSwiftApp/AppDelegate.swift
OptimizelySwiftSDK.xcodeproj/project.pbxproj
Sources/Implementation/DefaultNotificationCenter.swift
Sources/Utils/HandlerRegistryService.swift
Tests/OptimizelyTests-Common/NotificationCenterTests.swift
Tests/OptimizelyTests-MultiClients/NotificationCenterTests_MultiClients.swift

Fix NotificationCenter to support multiple clients (sdkKeys).
- full thread-safety for additional concurrency requirements
- no resource conflicts for multiple sdkKeys support

fix(notification): add support for multiple clients

---

DemoObjCApp/DemoObjcApp.xcodeproj/xcshareddata/xcschemes/DemoObjctvOS.xcscheme
DemoSwiftApp/Samples/SamplesForAPI.swift
Sources/Data Model/Attribute.swift
Sources/Data Model/Audience/Audience.swift
Sources/Data Model/Audience/ConditionHolder.swift
Sources/Data Model/Event.swift
Sources/Data Model/Experiment.swift
Sources/Data Model/FeatureFlag.swift
Sources/Data Model/Project.swift
Sources/Data Model/ProjectConfig.swift
Sources/Data Model/Variation.swift
Sources/Optimizely+Decide/OptimizelyClient+Decide.swift
Sources/Optimizely/OptimizelyClient.swift
Sources/Optimizely/OptimizelyConfig+ObjC.swift
Sources/Optimizely/OptimizelyConfig.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_OptimizelyConfig.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_OptimizelyConfig_Objc.m
Tests/OptimizelyTests-Common/OptimizelySwiftSDKiOSTests.swift
Tests/OptimizelyTests-DataModel/AudienceTests.swift
Tests/OptimizelyTests-DataModel/ConditionHolderTests.swift
Tests/OptimizelyTests-DataModel/ExperimentTests.swift
Tests/TestData/optmizelyConfig/optimizely_config_datafile.json
Tests/TestData/optmizelyConfig/optimizely_config_expected.json

The following new public properties are added to OptimizelyConfig:
- sdkKey
- environmentKey
- attributes
- audiences
- events
- experimentRules and deliveryRules to OptimizelyFeature
- audiences to OptimizelyExperiment

feat(OptimizelyConfig): add new fields to OptimizelyConfig

---

CHANGELOG.md

- add a deprecation note (OptimizelyFeature:experimentsMap) to Changelog

chore: add OptimizelyConfig deprecation note to changelog

---

Sources/Optimizely/OptimizelyError.swift

- Noticed this printing to our console earlier today; typo now corrected.
- Confirming everything builds & passes on CI should be sufficient here
- N / A

Correct minor typo in error message - 'experiement'

---

Sources/Customization/DefaultDatafileHandler.swift
Sources/Customization/DefaultEventDispatcher.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_DatafileHandler.swift
Tests/OptimizelyTests-Common/DatafileHandlerTests.swift
Tests/OptimizelyTests-Common/EventDispatcherTests.swift
Tests/OptimizelyTests-Common/NetworkReachabilityTests.swift
Tests/OptimizelyTests-MultiClients/DatafileHandlerTests_MultiClients.swift
Tests/OptimizelyTests-MultiClients/MultiClientsTests.swift
Tests/TestUtils/MockUrlSession.swift

According to Apple, [we should avoid creating instances of `URLSession`](https://developer.apple.com/videos/play/wwdc2017-709/?time=1977):
> But if you do allocate URLSessions dynamically, remember to clean up afterwards. Either finish tasks and invalidate or invalidate and cancel. But if you don't clean up, you'll leak memory.
In the project I'm working on, we got this weird error:
```
Error Domain=NSPOSIXErrorDomain
Code=28 
“No space left on device” 
UserInfo={_kCFStreamErrorCodeKey=28, _kCFStreamErrorDomainKey=1}
```
Googling that lead us to discover that "space" here is probably not referring to RAM or disk space, but that as of iOS 14 this error shows up when you have too many URLSessions going at once:
* [Stack Overflow](https://stackoverflow.com/questions/67318867/error-domain-nspo …

Fix invalidate url sessions

---

DemoObjCApp/DemoObjcApp.xcodeproj/xcshareddata/xcschemes/DemoObjciOS.xcscheme
DemoObjCApp/DemoObjcApp.xcodeproj/xcshareddata/xcschemes/DemoObjctvOS.xcscheme
DemoSwiftApp/DemoSwiftApp.xcodeproj/xcshareddata/xcschemes/DemoSwiftiOS.xcscheme
DemoSwiftApp/DemoSwiftApp.xcodeproj/xcshareddata/xcschemes/DemoSwifttvOS.xcscheme
DemoSwiftApp/DemoSwiftApp.xcodeproj/xcshareddata/xcschemes/DemoSwiftwatchOS.xcscheme
OptimizelySwiftSDK.xcodeproj/project.pbxproj
OptimizelySwiftSDK.xcodeproj/xcshareddata/xcschemes/OptimizelySwiftSDK-iOS.xcscheme
OptimizelySwiftSDK.xcodeproj/xcshareddata/xcschemes/OptimizelySwiftSDK-macOS.xcscheme
OptimizelySwiftSDK.xcodeproj/xcshareddata/xcschemes/OptimizelySwiftSDK-tvOS.xcscheme
OptimizelySwiftSDK.xcodeproj/xcshareddata/xcschemes/OptimizelySwiftSDK-watchOS.xcscheme
Sources/Customization/DefaultDatafileHandler.swift
Sources/Customization/DefaultEventDispatcher.swift
Sources/Customization/Protocols/OPTLogger.swift
Sources/Data Model/ProjectConfig.swift
Sources/Implementation/Datastore/DataStoreFile.swift
Sources/Implementation/Datastore/DataStoreUserDefaults.swift
Sources/Implementation/DefaultBucketer.swift
Sources/Implementation/DefaultDecisionService.swift
Sources/Utils/Notifications.swift
Sources/Utils/ThreadSafeLogger.swift
Tests/OptimizelyTests-Batch-iOS/EventDispatcherTests_Batch.swift
Tests/OptimizelyTests-MultiClients/EventDispatcherTests_MultiClients.swift

This fixes a couple of possible sources of race conditions in ProjectConfig.
- A logger is created thread-safe in a lazy mode. This fixes a bug that the reference for the logger instance was not fully protected in synchronization.
- The static observer of {projectId, revision} changes in datafile is not necessary since the event-batcher checks them for 
batch boundaries. It's cleaned up in this fix since it becomes a source of tricky race conditions. 
- Fix unit tests covering loggers and event-batcher.
- [Issue #448](https://github.com/optimizely/swift-sdk/issues/448)

fix(ProjectConfig): remove sources of race conditions in ProjectConfig

---

README.md

- Updated the dev doc URLs in the readme
The "why", or other context.
As part of the larger Optimizely developer documentation consolidation, the links to the documentation have changed.
N/A
N/A

Updating doc urls

---

.github/workflows/integration_tests.yml
.github/workflows/swift.yml

- Git actions updated to run FSC on git actions.
- Need to change travisci-tools branch from `mnoman/gitActions` to `master`

feat: updated for fsc git action

---

.github/workflows/unit_tests.yml
DemoSwiftApp/DemoSwiftApp.xcodeproj/xcshareddata/xcschemes/DemoSwiftwatchOS.xcscheme

- github actions deprecate macOS-10.15. It's replaced to macOS-latest.

chore: update the macos version in github actions

---

.github/workflows/swift.yml
.github/workflows/unit_tests.yml
Scripts/prepare_simulator.sh

- github actions changed iOS support, so building failed for old unit tests settings. Update OS + xcode versions to valid values. 
- add OS15 to the unit tests.
- change min OS simulator to 13.x (due to github actions support limitation)
- add more instructions for future update (github actions iOS support is vulnerable)
- pass all tests in github actions
- OASIS-8472

chore: update unit tests settings for github actions

---

Sources/Data Model/DispatchEvents/BatchEvent.swift
Sources/Implementation/Events/BatchEventBuilder.swift
Tests/OptimizelyTests-Common/BatchEventBuilderTest.swift
Tests/OptimizelyTests-Common/BatchEventBuilderTests_EventTags.swift

The revenue and value fields of events are changed to integer and float types. 
- These changes are for internal only. There will be no change visible to users.
- They were implemented as AttributeValue type (the core types were validated when extracted).
- Pass existing unit and FSC tests
- FSSDK-8562
- https://github.com/optimizely/swift-sdk/issues/244

fix: change the types of event revenue and value fields

---

DemoObjCApp/DemoObjcApp.xcodeproj/project.pbxproj
DemoObjCApp/DemoObjcApp.xcodeproj/xcshareddata/xcschemes/DemoObjciOS.xcscheme
DemoObjCApp/DemoObjcApp.xcodeproj/xcshareddata/xcschemes/DemoObjctvOS.xcscheme
DemoObjCApp/Samples/SamplesForAPI.m
DemoSwiftApp/DemoSwiftApp.xcodeproj/project.pbxproj
DemoSwiftApp/DemoSwiftApp.xcodeproj/xcshareddata/xcschemes/DemoSwiftiOS.xcscheme
DemoSwiftApp/DemoSwiftApp.xcodeproj/xcshareddata/xcschemes/DemoSwifttvOS.xcscheme
DemoSwiftApp/DemoSwiftApp.xcodeproj/xcshareddata/xcschemes/DemoSwiftwatchOS.xcscheme
OptimizelySwiftSDK.xcodeproj/project.pbxproj
OptimizelySwiftSDK.xcodeproj/xcshareddata/xcschemes/OptimizelySwiftSDK-iOS.xcscheme
OptimizelySwiftSDK.xcodeproj/xcshareddata/xcschemes/OptimizelySwiftSDK-macOS.xcscheme
OptimizelySwiftSDK.xcodeproj/xcshareddata/xcschemes/OptimizelySwiftSDK-tvOS.xcscheme
OptimizelySwiftSDK.xcodeproj/xcshareddata/xcschemes/OptimizelySwiftSDK-watchOS.xcscheme
Sources/Data Model/Audience/AttributeValue.swift
Sources/Data Model/Audience/UserAttribute.swift
Sources/Optimizely/OptimizelyConfig+ObjC.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_OptimizelyConfig.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_OptimizelyConfig_Objc.m
Tests/OptimizelyTests-DataModel/AttributeValueTests.swift

- Remove warnings about deprecated OptimizelyConfig.experimentsMap (used in SDK for objc wrapper)
- Clean up other lint errors
- Pass all existing unit and FSC tests.
- FSSDK-8671

fix: clean up build warnings

---

.github/workflows/swift.yml
.github/workflows/unit_tests.yml
Sources/ODP/OdpEventManager.swift
Sources/ODP/OdpManager.swift
Sources/ODP/OdpVuidManager.swift
Tests/OptimizelyTests-Common/OdpEventManagerTests.swift
Tests/OptimizelyTests-Common/OdpManagerTests.swift
Tests/OptimizelyTests-Common/OdpVuidManagerTests.swift

- When a vuid is used as a userId (UserContext is created without userId), identifyUser event should not include redundant vuids in event identifiers.
unit tests
- FSSDK-8413

fix(ats): enhance or fix ODP integration

---

Sources/Optimizely+Decide/OptimizelyClient+Decide.swift
Sources/Optimizely/OptimizelyClient.swift
Tests/OptimizelyTests-Common/OptimizelyUserContextTests_ODP.swift
Tests/TestData/odp/decide_audience_segments.json

Fix a bug that ODP event is automatically dispatched for legacy APIs (activate, etc by sharing createUserContext).
- Unit test validating no ODP event
- [FSSDK-8413](https://jira.sso.episerver.net/browse/FSSDK-8413)

feat(ats): remove auto ODP identify events from legacy APIs

---

Sources/ODP/OdpEventManager.swift
Sources/ODP/OdpManager.swift
Sources/ODP/OdpSegmentManager.swift
Tests/OptimizelyTests-Common/OdpEventApiManagerTests.swift
Tests/OptimizelyTests-Common/OdpEventManagerTests.swift
Tests/OptimizelyTests-Common/OdpManagerTests.swift
Tests/OptimizelyTests-Common/OdpSegmentManagerTests.swift
Tests/OptimizelyTests-Common/OptimizelyUserContextTests_ODP_2.swift

OdpConfig is removed from OdpEventManager/OdpSegmentManager init params, which will be better for supporting custom OdpManager.
- Unit tests
- [FSSDK-8843](https://jira.sso.episerver.net/browse/FSSDK-8843)

fix(ats): remove odpConfig from OdpEventManager/OdpSegmentManager init params

---

Sources/Extensions/OptimizelyClient+Extension.swift
Sources/ODP/OdpConfig.swift
Sources/ODP/OdpEvent.swift
Sources/ODP/OdpEventApiManager.swift
Sources/ODP/OdpEventManager.swift
Sources/ODP/OdpManager.swift
Sources/ODP/OdpSegmentApiManager.swift
Sources/ODP/OdpSegmentManager.swift
Sources/Optimizely/OptimizelyClient.swift
Tests/OptimizelyTests-Common/DecisionListenerTests.swift

- Provides access to some ODP classes for testing purpose.
- All tests should pass
- FSC ODP Result: https://github.com/optimizely/fullstack-sdk-compatibility-suite/actions/runs/4122123976/jobs/7118530491
- FSSDK-8042

refact(odp): Allows support for ODP testing using FSC.

---

README.md

- Updates readme replacing Full Stack with Feature Experimentation
- All tests should pass
- [FSSDK-8951](https://jira.sso.episerver.net/browse/FSSDK-8951)

[FSSDK-8951]: Updates readme replacing Full Stack with Feature Experimentation.

---

.travis.yml

- Updating travis release version to 3.10.2

[FSSDK-8951] Updating travis release version to 3.10.2

---

.github/workflows/swift.yml
.github/workflows/unit_tests.yml
Scripts/test_all.sh
Sources/Extensions/OptimizelyClient+Extension.swift
Sources/ODP/OdpEventApiManager.swift
Sources/ODP/OdpEventManager.swift
Sources/ODP/OdpManager.swift
Sources/ODP/OdpSegmentManager.swift
Sources/Optimizely+Decide/OptimizelyClient+Decide.swift
Sources/Optimizely/OptimizelyClient.swift
Sources/Optimizely/OptimizelyError.swift
Sources/Utils/Constants.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_ODP.swift
Tests/OptimizelyTests-Common/OdpManagerTests.swift

Add more support for sendOdpEvent error handling:
- empty string for action: throws odpInvalidAction
- nil/empty for type: use default "fullstack" type
- replace identifiers alias (fs-user-id/FS-USER-ID/FS_USER_ID) with fs_user_id
Include other clean-ups:
- upgrade macOS (12), xcode(14.3), and simulators (15.5 and 16.1) in github actions (tests hangs with old versions).
- upgrade local tests (Scrtips/test_all.sh) to cover a range of iOS versions (github actions not good for full coverage).
- Add unit tests covering all cases
- [FSSDK-9062](https://jira.sso.episerver.net/projects/FSSDK/issues/FSSDK-9062)

[FSSDK-9062] add more support for sendOdpEvent error handling

---

.github/workflows/swift.yml
Sources/Customization/DefaultEventDispatcher.swift
Sources/ODP/OdpEventManager.swift
Sources/ODP/OdpSegmentManager.swift
Sources/Utils/LogMessage.swift
Tests/OptimizelyTests-Common/OdpEventManagerTests.swift
Tests/OptimizelyTests-Common/OptimizelyDecisionTests.swift
Tests/TestUtils/OTUtils.swift

- Add support for retries (up to 3 times) when ODP event dispatch fails on connection or server errors. ODP events are discarded after max retries.
- Check reachability before dispatching to avoid discarding all events in the queue when network is down.
- Add unit tests with event errors and reachability scenarios
- [FSSDK-9061](https://jira.sso.episerver.net/browse/FSSDK-9061)

[FSSDK-9061] fix retries on odp event failures

---

DemoSwiftApp/AppDelegate.swift
DemoSwiftApp/Samples/SamplesForAPI.swift
Sources/Optimizely+Decide/OptimizelyUserContext.swift
Tests/OptimizelyTests-Common/OptimizelyUserContextTests_ODP.swift

- blocking version of `fetchQualifiedSegments` is added (convenient with asynchronous OptimizelyClient start)
- clean up non-blocking version of `fetchQualifiedSegments` (remove segments in completion handler)
- add unit tests for blocking `fetchQualifiedSegments`
- [FSSDK-8554](https://jira.sso.episerver.net/browse/FSSDK-8554)

[FSSDK-8554] add blocking version of fetchQualifiedSegments

---

Sources/ODP/OdpSegmentApiManager.swift
Tests/OptimizelyTests-Common/OdpSegmentApiManagerTests.swift

Support a new format for ODP `InvalidIdentifierException` (when SDK fetches segments with a non-registered userId).
```
"extensions": {
"code": "INVALID_IDENTIFIER_EXCEPTION",
"classification": "DataFetchingException"
}
```
Add unit tests to cover the new response format.
- [FSSDK-9124](https://jira.sso.episerver.net/browse/FSSDK-9124)

[FSSDK-9124] fix for ODP INVALID_IDENTIFIER_EXCEPTION code

---

.github/workflows/swift.yml
Scripts/run_prep.sh

Fix issues for prepare-release
- fix "hub pull-request" cli 
- remove run-test.sh from prep process

[FSSDK-8918] chore: fix issues for prepare-release

---

.github/workflows/swift.yml
Scripts/run_release.sh

Fix release script
- add COCOAPODS_TRUNK_TOKEN env variable.
- auto tag generation can be skipped when retried.

[FSSDK-8918] chore: fix release script

---

CHANGELOG.md
Scripts/build_all.sh
Scripts/run_prep.sh
Sources/Protocols/BackgroundingCallbacks.swift
Sources/Utils/Utils.swift
Tests/OptimizelyTests-Common/OdpEventManagerTests.swift

Cocoapods complain iOS specific features (UIKit, UIDevice) for other platforms.
Fix to support all platforms
- build with other platforms (macOS, watchOS)

[FSSDK-8918] fix: clean up UIKit import errors

---

Sources/Customization/DefaultDatafileHandler.swift
Tests/OptimizelyTests-Common/DatafileHandlerTests.swift
Tests/OptimizelyTests-Common/NetworkReachabilityTests.swift
Tests/OptimizelyTests-MultiClients/DatafileHandlerTests_MultiClients.swift
Tests/TestUtils/MockUrlSession.swift

- Adds a check to only save valid datafile in cache.
- New unit tests added
- All previous unit tests should pass
- [FSSDK-6907](https://jira.sso.episerver.net/browse/FSSDK-6907)

[FSSDK-6907]: Adds a check to only save valid datafile in cache.

---

Sources/Extensions/OptimizelyClient+Extension.swift
Sources/Utils/LogMessage.swift

-  Implements a warning log for polling interval less than 30s
- [FSSDK-9508](https://jira.sso.episerver.net/browse/FSSDK-9508)

 [FSSDK-9508] refact: Implements a warning log for polling interval less than 30s

---

Sources/Optimizely/OptimizelyClient.swift
Sources/Optimizely/OptimizelyConfig.swift
Tests/OptimizelyTests-APIs/OptimizelyClientTests_OptimizelyConfig.swift
Tests/OptimizelyTests-DataModel/ProjectConfigTests.swift

When duplicate experiment key found in the data file, SDK returns correct experiment map in  OptimizelyConfig
- Keep latest experiment key, found in the datafile experiment list
- Add warning log "Duplicate keys found in datafile: {key-name}"
- Add test case for OptimizelyConfig with duplicate key
- [FSSDK-9776](https://jira.sso.episerver.net/browse/FSSDK-9776)

[FSSDK-9776] handle duplicate experiment key

---

.github/workflows/swift.yml
CHANGELOG.md
README.md

- Upload task request issue fixed
- App privacy manifest file added
- Handle duplicate keys in experiment
- All previous test should pass
- [FSSDK-9744](https://jira.sso.episerver.net/browse/FSSDK-9744)

[FSSDK-9744] chore: prepare  release 3.10.3

---

.github/workflows/swift.yml
CHANGELOG.md
OptimizelySwiftSDK.xcodeproj/project.pbxproj
README.md
Scripts/run_unit_tests.sh
Sources/Customization/DefaultEventDispatcher.swift
Sources/Optimizely/OptimizelyClient.swift
Sources/Optimizely/OptimizelyConfig.swift
Sources/Supporting Files/PrivacyInfo.xcprivacy
Tests/OptimizelyTests-APIs/OptimizelyClientTests_OptimizelyConfig.swift

- Upload task request issue fixed
- App privacy manifest file added
- Handle duplicate keys in experiment
- All previous test should pass
- [FSSDK-9744](https://jira.sso.episerver.net/browse/FSSDK-9744)

Prepare release 3.10.3

---

.github/workflows/swift.yml

- Hub command not found for pre-release workflow. Hub installation task added into swift.yml workflow.
- [Before fix] (https://github.com/optimizely/swift-sdk/actions/runs/7398824524/job/20128860808)
- [After fix] (https://github.com/optimizely/swift-sdk/actions/runs/7399129592/job/20129831283)
- `prepare_for_release` and `release` workflow should pass.
- [FSSDK-9899](https://jira.sso.episerver.net/browse/FSSDK-9899)

[FSSDK-9899] fix:  hub, command not found

---

Sources/Supporting Files/PrivacyInfo.xcprivacy

- Current value was supplied by us, but the value should align with the list [CA92.1, 1C8F.1, C56D.1, AC6B.1] [Ref](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)
- N/A
- [FSSDK-9945](https://jira.sso.episerver.net/browse/FSSDK-9945)

[FSSDK-9945] fix: privacy manifest file value for required reason API

---

Package.swift

- SPM support added to process the privacy manifest info file. [Resource](https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html#resource)
- Swift tools version updated to 5.4 [About the Swift Tools Version](https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html#)
- Update package compiling swift version. [SwiftVersion](https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html#swiftversion)
- [FSSDK-9950](https://jira.sso.episerver.net/browse/FSSDK-9950)

[FSSDK-9950] chore: SPM support added to process privacy manifest

---

.github/workflows/swift.yml
CHANGELOG.md
README.md

- Prepare for release 4.0.0
- [FSSDK-8553](https://jira.sso.episerver.net/browse/FSSDK-8553)

[FSSDK-8553] chore: prepare for release 4.0.0

---

.github/workflows/swift.yml
CHANGELOG.md
OptimizelySwiftSDK.podspec
Package.swift
README.md
Sources/Supporting Files/PrivacyInfo.xcprivacy

- Value for required reason API fixed at privacy manifest file. ([#541](https://github.com/optimizely/swift-sdk/pull/541))
- Add coccoapods support to bundle privacy manifest file. ([#542](https://github.com/optimizely/swift-sdk/pull/542))
- Add SPM support to bundle privacy manifest file. ([#544](https://github.com/optimizely/swift-sdk/pull/544))
- All previous test should pass
- [FSSDK-9952](https://jira.sso.episerver.net/browse/FSSDK-9952)

[FSSDK-9952] chore: prepare for release 3.10.5

---

.github/workflows/integration_tests.yml
.github/workflows/unit_tests.yml

Instead of directly using variables that can contain user input, new intermediate variables were introduced so that script injection attacks could be mitigated. 
- [FSSDK-10665](https://jira.sso.episerver.net/browse/FSSDK-10665)

[FSSDK-10665] fix: Github Actions YAML files vulnerable to script injections corrected

---

OptimizelySwiftSDK.xcodeproj/project.pbxproj
Sources/Implementation/DefaultDecisionService.swift
Sources/Implementation/UserProfileTracker.swift
Sources/Optimizely+Decide/OptimizelyClient+Decide.swift
Tests/OptimizelyTests-Common/DecisionListenerTests.swift
Tests/OptimizelyTests-Common/DecisionServiceTests_Features.swift

- Currently, decideForKeys loops over the list of flags and calls decide for each, which in turn calls ups. So for decideForKeys, there is two calls per flag to UPS. This PR batches UPS calls when using decideForKeys.
- [FSSDK-10771](https://jira.sso.episerver.net/browse/FSSDK-10771)

[FSSDK-10771] Implement UPS request batching for decideForKeys

---

.github/workflows/unit_tests.yml

- Artifact actions v3 will be deprecated by December 5
- All testcases should be passed
- [FSSDK-10876](https://jira.sso.episerver.net/browse/FSSDK-10876)

[FSSDK-10876] chore: migrate artifact to v4 

---

.github/workflows/swift.yml
.github/workflows/unit_tests.yml
Sources/Data Model/Audience/AttributeValue.swift
Tests/OptimizelyTests-Common/BatchEventBuilderTests_EventTags.swift
Tests/OptimizelyTests-Common/DecisionServiceTests_Experiments.swift
Tests/OptimizelyTests-DataModel/AttributeValueTests.swift
Tests/OptimizelyTests-DataModel/UserAttributeTests.swift

- Event tags support nested objects
- Fix the workflow simulator version
- All previous test cases should be passed
- [FSSDK-11036](https://jira.sso.episerver.net/browse/FSSDK-11036)

[FSSDK-11036] fix: event tags support nested objects

---

.github/workflows/swift.yml
.github/workflows/unit_tests.yml

- Follow up PR after updating simulator matrix
- All existing tests should be passed
- [FSSDK-11036](https://jira.sso.episerver.net/browse/FSSDK-11036)

[FSSDK-11036] chore: revert workflow branch to master

---

OptimizelySwiftSDK.xcodeproj/project.pbxproj
Sources/Data Model/Experiment.swift
Sources/Data Model/ExperimentCore.swift
Sources/Data Model/Holdout.swift
Sources/Optimizely/OptimizelyConfig.swift
Tests/OptimizelyTests-DataModel/HoldoutTests.swift

- Create a new Holdout model
- Declare an ExperimentCore protocol to share common properties between Experiment and Holdout
- Update the Experiment model to conform to ExperimentCore and align with shared properties.
- Holdout model test cases added
- [FSSDK-11371]

[FSSDK-11371] parsing holdout section from the datafile

---

OptimizelySwiftSDK.xcodeproj/project.pbxproj
Sources/Data Model/FeatureFlag.swift
Sources/Data Model/HoldoutConfig.swift
Sources/Implementation/DecisionInfo.swift
Sources/Implementation/DefaultBucketer.swift
Sources/Implementation/DefaultDecisionService.swift
Sources/Implementation/Events/BatchEventBuilder.swift
Sources/Optimizely/OptimizelyClient.swift
Sources/Protocols/OPTBucketer.swift
Sources/Utils/Constants.swift
Sources/Utils/LogMessage.swift
Tests/OptimizelyTests-Common/BucketTests_HoldoutToVariation.swift
Tests/OptimizelyTests-Common/DecisionListenerTests.swift
Tests/OptimizelyTests-Common/DecisionServiceTests_Features.swift
Tests/OptimizelyTests-Common/DecisionServiceTests_Features_Holdouts.swift
Tests/OptimizelyTests-Common/DecisionServiceTests_Holdouts.swift
Tests/OptimizelyTests-Common/OptimizelyUserContextTests_Decide_Holdouts.swift
Tests/OptimizelyTests-Common/OptimizelyUserContextTests_Decide_Reasons.swift
Tests/OptimizelyTests-Common/OptimizelyUserContextTests_Decide_With_Holdouts_Reasons.swift
Tests/OptimizelyTests-DataModel/HoldoutTests.swift
Tests/TestUtils/MockBucketer.swift

- Added support for holdout groups in decision-making logic.
- Introduced `ExperimentCore` to replace `Experiment` in several methods across the codebase.
- Refactored `DefaultDecisionService` for improved readability and holdout support.
- Added the `getVariationForHoldout` method to evaluate holdout conditions and bucket users into holdouts.
- Enhanced the `OPTBucketer` protocol by adding the new `bucketToVariation` method.
- Introduced new test files, including `BucketTests_HoldoutToVariation.swift`, `DecisionServiceTests_Features_Holdouts.swift`, `OptimizelyUserContextTests_Decide_Holdouts.swift`, `OptimizelyUserContextTests_Decide_With_Holdouts_Reasons.swift`
- FSSDK-11373

[FSSDK-11373] add holdout support and refactor decision logic in DefaultDecisionService
