Scripts/run_prep.sh
need to do it as a separate step
=> ci(travis): pod install no longer updates

README.md
add cocoapods badge to readme.
=> (chore): add cocoapods tags

.travis.yml
drew inspiration from https://github.com/xcpretty/xcpretty/issues/17#issuecomment-30343303
=> make "xcodebuild test" fail when tests fail

OptimizelySwiftSDK.xcodeproj/project.pbxproj
Set the "Allow app extensions only" flag in build settings to support App Extension
JIRA #5729
=> chore: turn on allow-app-extensions-only flag

DemoSwiftApp/AppDelegate.swift, Tests/OptimizelyTests-Common/EventDispatcherTests_Batch.swift
- add test case which add extra test for logEvent notification
- this also can be used to collect events to be used for offline Event Validation
=> chore: add test case for event validator

Scripts/test_all.sh
fix device os versions of test_all scripts
=> chore: prepare for release 3.2.0

OptimizelySwiftSDK.xcodeproj/project.pbxproj
A few test JSON files wrongly included in the framework bundle. Cleaned them up.
=> chore: clean up test files in the product bundle

Sources/Data Model/FeatureVariable.swift, Sources/Optimizely/OptimizelyClient+ObjC.swift, Sources/Optimizely/OptimizelyClient.swift, Sources/Optimizely/OptimizelyError.swift, Sources/Utils/Constants.swift, Tests/OptimizelyTests-APIs/OptimizelyClientTests_Invalid.swift, Tests/OptimizelyTests-APIs/OptimizelyClientTests_ObjcAPIs.m, Tests/OptimizelyTests-APIs/OptimizelyClientTests_Others.swift, Tests/OptimizelyTests-APIs/OptimizelyClientTests_Valid.swift, Tests/OptimizelyTests-Common/DecisionListenerTests.swift, Tests/OptimizelyTests-DataModel/FeatureVariableTests.swift, Tests/TestData/api_datafile.json
- added GetAllFeatureVariables public API.
- FSC should pass.
- Added Unit tests.
=> feat: added GetAllFeatureVariables API.

Sources/Implementation/DefaultDecisionService.swift, Tests/OptimizelyTests-APIs/OptimizelyClientTests_Variables.swift, Tests/OptimizelyTests-Common/DecisionServiceTests_Features.swift
- Added tests for target-rollout variables.
- Updated code to return nil if no experiments are present in rollout.
- FSC should pass.
- https://optimizely.atlassian.net/browse/OASIS-6437
=> refact(targeted-rollouts): Adding tests for targeted-rollout variables.

.travis.yml
- Adding source clear stage as cron. A copy of #338
=> chore: Add source clear stage.

Sources/Data Model/Audience/SemanticVersion.swift, Tests/OptimizelyTests-DataModel/SemanticVersionTests.swift
=> fix: add tests for blanks as invalid

Sources/Data Model/Audience/SemanticVersion.swift, Sources/Data Model/Audience/UserAttribute.swift, Tests/OptimizelyTests-DataModel/SemanticVersionTests.swift, Tests/OptimizelyTests-DataModel/UserAttributeTests_Evaluate.swift
fix fsc tests that are failing
=> fix: fix errors on FSC that are valid errors for semantic versioning

.travis.yml, Sources/Data Model/Audience/ConditionHolder.swift, Tests/OptimizelyTests-DataModel/ExperimentTests.swift
- add more tests for audience serialization (empty audiences, NOT conditions)
=> fix(OptimizelyConfig): add more tests for experiment audiences serialization

Sources/Optimizely/OptimizelyConfig.swift
Add a warning comments about experimentsMap with key conflicts.
=> chore: add conflicts warning for experimentsMap

pull_request_template.md
=> chore: add a PR template

.travis.yml, CHANGELOG.md, README.md
=> chore: prepare for release 3.9.0

Sources/Optimizely+Decide/OptimizelyUserContext.swift, Tests/OptimizelyTests-Common/OptimizelyUserContextTests_ForcedDecisions.swift
- Remove config-ready check from forced-decision apis
- Unit and FSC tests
=> fix(ForcedDecision): remove config-ready check from forced-decision apis

Sources/Data Model/ProjectConfig.swift, Sources/Implementation/DefaultDecisionService.swift, Sources/Optimizely+Decide/OptimizelyClient+Decide.swift, Sources/Optimizely+Decide/OptimizelyUserContext.swift, Sources/Protocols/OPTDecisionService.swift, Tests/OptimizelyTests-Common/DecisionServiceTests_Others.swift, Tests/OptimizelyTests-Common/OptimizelyUserContextTests_ForcedDecisions.swift
- Move forced-decision-validation from OptimizelyUserContext to DecisionService
- Add more unit tests
=> fix(ForcedDecision): move forced-decision-validation to DecisionService

.travis.yml, CHANGELOG.md, README.md
=> chore: prepare for release 3.10.0

.github/workflows/source_clear_cron.yml, .github/workflows/swift.yml, README.md
- Fixing issue with source clear cron failing because of cocoapod's installation.
- Cron job should run successfully.
=> fix(srcclr): Fixing source clear.

.github/workflows/swift.yml
- action files are now referring to master, all the latest code exists there.
FSC must pass.
- "THING-1234" or "Fixes #123"
=> fix: updated branch to master

.github/workflows/swift.yml
- change a branch for github actions workflow to master.
=> chore: change a branch for github actions workflow

.github/workflows/swift.yml
restore back to master branch
- FSSDK-0000 (N/A)
=> chore: restore workflow dependency to master version

README.md
Add a note to README about fixing SPM name conflicts.
- [FSSDK-8229](https://jira.sso.episerver.net/browse/FSSDK-8229)
=> chore: update README for SPM name conflict

.github/workflows/swift.yml, CHANGELOG.md
Prepare for release 4.0.0-beta
=> [FSSDK-8918] chore: prepare for release 4.0.0-beta

.github/workflows/swift.yml, Scripts/run_prep.sh, Scripts/test_all.sh
Fix cocopods version and home env for run_prep.sh
=> [FSSDK-8918] chore: fix run_prep script

.github/workflows/swift.yml, CHANGELOG.md, Scripts/run_prep.sh, Scripts/test_all.sh, Tests/OptimizelyTests-Common/OdpEventManagerTests.swift
Add force flag for prep branch push (so we can test and debug).
=> [FSSDK-8918] chore: fix prepare script

OptimizelySwiftSDK.podspec, Sources/Utils/SDKVersion.swift
=> ci(git-action): auto release prep for 4.0.0-beta

Scripts/run_release.sh
fix git describe error in run_release
The "why", or other context.
- FSSDK-1234
=> chore: fix git describe error

.github/workflows/swift.yml, Scripts/run_release.sh
Fix errors or cocoapods release
- [FSSDK-123]
=> chore: fix errors for cocoapods release

.github/ISSUE_TEMPLATE/BUG-REPORT.yml, .github/ISSUE_TEMPLATE/ENHANCEMENT.yml, .github/ISSUE_TEMPLATE/FEATURE-REQUEST.md, .github/ISSUE_TEMPLATE/config.yml
- Update Github Issue Templates
- [FSSDK-9556](https://jira.sso.episerver.net/browse/FSSDK-9556)
- [Preview](https://github.com/optimizely/javascript-sdk/issues/842)
=> [FSSDK-9556]: Update Github Issue Templates.

Sources/Customization/DefaultEventDispatcher.swift
- Upload task request issue fixed
- All previous tests should pass
- [FSSDK-9731](https://jira.sso.episerver.net/browse/FSSDK-9731)
=> [FSSDK-9371]fix: Upload task request contains body

OptimizelySwiftSDK.xcodeproj/project.pbxproj, Sources/Supporting Files/PrivacyInfo.xcprivacy
- App privacy manifest file added
- N/A
- [FSSDK-9709](https://jira.sso.episerver.net/browse/FSSDK-9709)
=> [FSSDK-9709] feat: App privacy manifest file added

.github/workflows/swift.yml, CHANGELOG.md, README.md
- App privacy manifest file added
- All previous test should pass
- [FSSDK-9744](https://jira.sso.episerver.net/browse/FSSDK-9744)
=> [FSSDK-9744] chore: prepare release 3.10.4

OptimizelySwiftSDK.podspec, Sources/Utils/SDKVersion.swift
=> ci(git-action): auto release prep for 3.10.4

OptimizelySwiftSDK.podspec, Sources/Utils/SDKVersion.swift
=> ci(git-action): auto release prep for 4.0.0

OptimizelySwiftSDK.podspec, Sources/Utils/SDKVersion.swift
=> ci(git-action): auto release prep for 3.10.5

OptimizelySwiftSDK.podspec, Sources/Utils/SDKVersion.swift
=> ci(git-action): auto release prep for 4.1.0

OptimizelySwiftSDK.podspec, Sources/Utils/SDKVersion.swift
=> ci(git-action): auto release prep for 5.0.0

.github/workflows/swift.yml, CHANGELOG.md, README.md
- Nested event tags support release
- All test cases should be passed
- [FSSDK-11111](https://jira.sso.episerver.net/browse/FSSDK-11111)
=> [FSSDK-11111] chore: prepare release 5.1.0

OptimizelySwiftSDK.podspec, Sources/Utils/SDKVersion.swift
=> ci(git-action): auto release prep for 5.1.0

OptimizelySwiftSDK.xcodeproj/project.pbxproj, Sources/CMAB/CmabClient.swift, Tests/OptimizelyTests-Common/CMABClientTests.swift
-  Implement cmab client
- FSSDK-11145
=> [FSSDK-11145] chore: implement cmab client
